- .gitignore
- demo/app.jsx
- docs/docs.jsx
- package.json
- Ignored the npm-debug.log.* https://github.com/FormidableLabs/victory-pie/issues/9 
- Update to React 0.14 and victory-animation 0.0.8
/cc @boygirl
> Update to React 0.14

- docs/docs.jsx
- docs/theme.js
- package.json
Screenshots!
[...]
This PR builds off of https://github.com/FormidableLabs/victory-pie/pull/11 and is dependent on the latest `master` of ecology.
> Better styles for docs

- docs/index.html
- docs/static-index.jsx
- docs/static-render-entry.jsx
cc/ @david-davidson 
that should clear that up
> make the naming less confusing

- demo/app.jsx
- src/components/victory-pie.jsx
The forgotten width / height / padding PR. Same as the others
> use width height and padding props

- docs/app.jsx
- docs/docs.jsx
- docs/static-render-entry.jsx
- docs/webpack.config.dev.js
- docs/webpack.config.dist.js
- docs/webpack.config.hot.js
> Replicate victory-bar docs change

- package.json
https://github.com/FormidableLabs/victory/issues/98#issuecomment-165595339
> add warning to postinstall

- demo/demo.jsx
- src/components/slice-label.jsx
- src/components/slice.jsx
- src/components/victory-pie.jsx
- test/client/spec/components/victory-pie.spec.jsx
Like #46 except on pre-release branch
> (pre-release) Data accessors for victory-pie

- docs/ecology.md
Companion PR to https://github.com/FormidableLabs/victory-chart/pull/136
> Add Props heading, fix Docs links

- demo/demo.jsx
Animates the pies that weren't.
I think this change smoothed out the "warm" example. https://github.com/FormidableLabs/victory-pie/compare/demo-data-transitions-should-be-animated?expand=1#diff-3860df8740a869cde6dfb90663c634e3L109
> Fixes: FormidableLabs/victory-pie#57

- src/components/slice-label.jsx
> Consumes VictoryLabel refactoring to pass label as text prop

- .babelrc
- demo/demo.jsx
- docs/docs.jsx
- docs/static-index.jsx
- docs/static-render-entry.jsx
- package.json
- src/components/slice-label.jsx
- src/components/slice.jsx
- src/components/victory-pie.jsx
- src/index.js
- test/client/main.js
- test/client/spec/components/victory-pie.spec.jsx
cc/ @coopy 
this PR adds event handling, enzyme tests, support for babel 6, and memoization of get styles (it got missed in this repo)
also closes #57 and #55
> add event handling and enzyme tests

- src/components/slice-label.jsx
Depends on FormidableLabs/victory-core#26
Closes FormidableLabs/victory-pie#60
> prop data now datum in VictoryLabel

- demo/demo.jsx
- package.json
- src/components/victory-pie.jsx
Adds support for enter and exit transitions, and defines a default transition for VictoryPie
> add enter and exit transitions and demo

- package.json
https://github.com/FormidableLabs/victory/issues/258
> Upgrade react version to v15.1.0

- CHANGELOG.md
- demo/demo.js
- docs/docs.js
- docs/ecology.md
- package.json
- src/components/helper-methods.js
- src/components/victory-pie.js
- test/client/spec/components/victory-pie.spec.js
depends on https://github.com/FormidableLabs/victory-core/pull/61
VictoryPie can expose the props of all its rendered components for the VictorySharedEvents wrapper to use. https://gist.github.com/boygirl/367b76ab7d6144f43ce3e6a5228fde40
> Shared events

- README.md
- docs/README.md
- docs/ecology.md
- package.json
- Point links to formidable.com/open-source/victory
- Upgrade `ecology` for react@15
- Update `README.md` in `docs/`
> Bug: Update links in /docs

- .babelrc
- .travis.yml
- package.json
- src/components/victory-pie.js
cc/ @vakhtang 
Not ready to merge. Depends on changes in `builder-victory-component` and `victory-core`
> [WIP] Native

- docs/docs.js
- package.json
This will append either an internal or relative icon to links within the docs.
> Add appendLinkIcon function to ecology

- docs/docs.js
- package.json
Will load placeholder boxes on initial render and fix https://github.com/FormidableLabs/formidable-landers/issues/23
> Add ecologyPlaygroundLoading func to docs

- demo/demo.js
Base: https://github.com/FormidableLabs/victory-pie/pull/103
Modify demos to use material theme.
/cc @ebrillhart @kylecesmat @boygirl
> Modify demos to use material theme

- package.json
- src/components/helper-methods.js
- src/components/victory-pie.js
depends on https://github.com/FormidableLabs/victory-core/pull/185
fixes FormidableLabs/victory#451
fixes FormidableLabs/victory#350
> fix data accessors on transitons

- README.md
Noticed a 404 in the README. :male_detective:
> Fix link to contributing in README

- src/components/helper-methods.js
- src/components/victory-pie.js
minor changes to support victory native update
> Support VictoryNative

- package.json
- src/components/victory-pie.js
uses new common methods from `add-events`
> use common methods from add-events

- src/components/helper-methods.js
closes https://github.com/FormidableLabs/victory/issues/568
> round label positions

- demo/demo.js
- package.json
- src/components/helper-methods.js
- src/components/victory-pie.js
Depends on https://github.com/FormidableLabs/victory-core/pull/265
Fixes https://github.com/FormidableLabs/victory/issues/639
adds translation to x and y label positions rather than translating the entire pie (slices and labels). Depends on a PR to victory-core that adds a translation to slices
> no group translation

- package.json
- src/components/victory-pie.js
Implements external event mutations for `victory-pie` components. 
Depends on https://github.com/FormidableLabs/victory-core/pull/324
> External Events

- README.md
> lank workflow
