- .npmignore
- DEVELOPMENT.md
cc/ @angelanicholas 
fun story!  if you don't have an `.npmignore` npm uses your `.gitignore` instead, which is why components weren't getting included correctly (npm was ignoring lib)
I added an `.npmignore` and updated the docs again after a review from Roemer.
> update release docs again, add .npmignore

- demo/app.jsx
- docs/ecology.md
- package.json
- src/components/slice-label.jsx
- src/components/slice.jsx
- src/components/victory-pie.jsx
- test/client/spec/components/victory-pie.spec.jsx
this PR
- switches to d3 modules
- breaks pie into small renderables
- supports functional styles
- renames `sliceColors` -> `colorScale` and adds support for default color scales from util, updates the docs to reflect this naming change
- adds a `labelComponent` prop
- adds test coverage
closes #29 
closes #28 
closes #27 
closes #26
> Small renderables

- README.md
`https` doesn't work with gh pages. Also update intro statement to be consistent with Ecology docs.
> Fix API doc link

- package.json
- src/components/slice-label.jsx
- src/components/slice.jsx
- src/components/victory-pie.jsx
cc/ @coopy 
this PR updates `victory-pie` to use the new `Helpers` namespace in `victory-util`. 
Merge after https://github.com/FormidableLabs/victory-util/pull/26 and https://github.com/FormidableLabs/victory-label/pull/38
> update for naming change in victory-util

- demo/demo.jsx
- package.json
- src/components/slice-label.jsx
- src/components/slice.jsx
- src/components/victory-pie.jsx
Following the same pattern as before.  Radium is present in devDeps for demo purposes, removed elsewhere.  Replaced `victory-*` with `victory-util`.  cc @boygirl
> Remove Radium

- README.md
- demo/demo.jsx
- package.json
I've added standard npm scripts and updated the README to have the minimum needed to get started on development.
- `npm start` runs `builder run hot`
- `npm test` runs `builder run check`
I've also fixed the demo app to clear the interval when the component unmounts.
/cc @tptee @boygirl
> Add `npm start` script and update README

- .eslintrc
- package.json
- test/.eslintrc
**DO NOT MERGE YET - DEPENDS ON CHANGE IN ARCHETYPE**
https://github.com/FormidableLabs/builder-victory-component/pull/50
This change adds local `.eslintrc` files that extend the archetype configuration files.
Local .eslintrc files in the tree enables integration with IDE/editor linting plugins, such as [linter-eslint](https://atom.io/packages/linter-eslint).
> Add local .eslintrc files

- demo/demo.jsx
- src/components/victory-pie.jsx
- test/client/spec/components/victory-pie.spec.jsx
Includes a (single) shallow test to assert the type of node matches that
provided in the props.
Replaces FormidableLabs/victory-pie#50
> Adds dataComponent prop to Pie

- demo/demo.js
- src/components/helper-methods.js
- src/components/victory-pie.js
This adds the ability to pass cornerRadius prop to VictoryPie, and get a result similar to this: https://www.npmjs.com/package/d3-shape#arc_cornerRadius
> add cornerRadius prop

- src/components/victory-pie.js
similar to default font increases in victory chart, this increases the default font size of labels for victory pie for better readability on smaller charts. @boygirl
> bumping up font size for pie labels

- demo/demo.js
- src/components/helper-methods.js
- src/components/victory-pie.js
- test/client/spec/components/victory-pie.spec.js
0 is valid text for labels, but undefined and null are not.
To fix this, I've added a function that is checking for this
edge cases.
> fix empty label on slices

- demo/demo.js
- docs/ecology.md
- package.json
- src/components/helper-methods.js
- src/components/victory-pie.js
- test/client/spec/components/victory-pie.spec.js
This PR
- supports events on the parent container component. parent event handlers are called with the event object as well as an object with `slices`,  `width`, `height`, and `styles`. 
- renders all data components before label components so that labels don't get overlapped by slices
closes https://github.com/FormidableLabs/victory-chart/issues/245
> Parent events

- demo/demo.js
- demo/index.html
- package.json
- src/components/helper-methods.js
- src/components/victory-pie.js
This PR adds theme support to Victory-Pie and adds some demos of the grayscale theme.
In reference to comments from https://github.com/FormidableLabs/victory-chart/pull/242 a link to the source code for grayscale in victory-core has been included in the props description as an example of a theme. (This link will be functional once https://github.com/FormidableLabs/victory-core/pull/71 has been merged).
@boygirl
> add theme support to victorypie and do some grayscale demos

- demo/demo.js
- src/components/victory-pie.js
Now for pie! 
Default the base styles of the chart components to be the grayscale theme. It brings consistency across the components and makes a very solid base for creating more themes.
Also alphabetized the object keys.
/cc @ebrillhart @boygirl @kylecesmat
> Change default styles to grayscale

- docs/docs.js
This will add the export buttons to the codeblocks when used in victory-docs
> Add code exports to docs

- package.json
- src/components/helper-methods.js
- src/components/victory-pie.js
- test/client/spec/components/victory-pie.spec.js
**depends on https://github.com/FormidableLabs/victory-core/pull/110**
This PR:
- removes all styles from `fallbackProps` across all components
- adds `theme: VictoryTheme.grayscale` to defaultProps
- adds checks for missing / expected style objects
> Simplify theme and fallback props

- demo/demo.js
- docs/victory-pie/ecology.md
- package.json
- src/components/helper-methods.js
- src/components/victory-pie.js
This PR 
- adds support for `VictoryTooltip`
- implements perf improvements
- adds a `labelRadius` prop that is easier to understand that trying to position labels with padding
- Sets text anchor and vertical anchor based on the angle of the pie slice
- Fixes demos and docs for modified styles
> update for tooltip, implement labelRadius

- src/components/victory-pie.js
- test/client/spec/components/victory-pie.spec.js
Automatically rendering tooltips in VictoryPortal was moving tooltips off screen rather than in the translated group that the pie is rendered into.
> dont render tooltips in portals for pie

- demo/demo.js
- src/components/victory-pie.js
cc/ @kenwheeler 
This fixes translations so that they are always centered when padding is equal regardless of dimension. Before I was just adding the radius and padding like a chump.
> translations are always centered for equal padding

- demo/demo.js
- src/components/helper-methods.js
fixes https://github.com/FormidableLabs/victory/issues/709
> fix asymmetric padding bug

- src/components/victory-pie.js
Role was not defined in victory-pie.js, which caused the function modifyProps to not work properly. 
It fixes the theme not being applied if the animate props was set (#841).
> Fixed role not defined in victory-pie.js

- src/components/victory-pie.js
- test/client/spec/components/victory-pie.spec.js
Fixes: FormidableLabs/victory#870
This fix uses the new `sortOrder` key. We can specify the `ascending` or `descending` order for `sortKey`
Tests will fail until we upgrade victory-core dependency with fix from https://github.com/FormidableLabs/victory-core/pull/322
Thanks!
> [ENH] Add sortOrder prop

- src/components/helper-methods.js
- src/components/victory-pie.js
Issue: [#650](https://github.com/FormidableLabs/victory/issues/650)
- Export all methods individually as named exports, instead of export all helpers as a default export in the form of an object
- Reorder the method definitions to counter eslint's `no-use-before-define` errors. This makes the diff look mighty weird, so it might be easier to look at the individual commits' diff
I'll be happy to make any changes you find necessary.
> Export helper methods as named exports

- src/components/helper-methods.js
This PR deprecates the ability to define style attrs directly on the data object. This will be a breaking change, but the upgrade path is minimal: 
If your data object looks like 
```
data={[
{ x: 1, y: 1, fill: "red", opacity: 0.2 }, 
...
]}
```
Add the following functional styles: 
```
style={{ data:  { fill: (d) => d.fill, opacity: (d) => d.opacity } }}
```
and everything will work as before
> remove ability to set styles from data

- CHANGELOG.md
- package-lock.json
- package.json
**Breaking Changes**
-[176](https://github.com/FormidableLabs/victory-pie/pull/176) Disable styles on data
This change deprecates Victory's ability to automatically pick up style attributes from the data object. This change will improve performance, but will be a breaking change for many users. Fortunately the upgrade path is simple:
If your data object looks like
```
data={[
{ x: 1, y: 1, fill: "red", opacity: 0.2 },
...
]}
```
Add the following functional styles:
```
style={{ data:  { fill: (d) => d.fill, opacity: (d) => d.opacity } }}
```
and everything will work as before.
Other changes:
-[177](https://github.com/FormidableLabs/victory-pie/pull/177) Audit lodash methods
> update victory core and changelog

- src/components/helper-methods.js
- src/components/victory-pie.js
Added support for radius prop to Victory-Pie. If radius prop is not present, radius is calculated from width, height, and padding as before.
-Added radius prop to propTypes in victory-pie.js
-Added check to getRadius in helper-methods.js
Closes https://github.com/FormidableLabs/victory/issues/910
> added radius prop to VictoryPie per issue #910
